name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno publish

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Build NPM package
        run: deno run -A scripts/build_npm.ts ${GITHUB_REF_NAME#v}
      - name: Publish
        run: npm publish ./npm_dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
