name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    environment: Runners
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Run tests
        run: deno task test
        env:
          E621_API_KEY: ${{ secrets.E621_API_KEY }}
          E926_API_KEY: ${{ secrets.E926_API_KEY }}
          DANBOORU_API_KEY: ${{ secrets.DANBOORU_API_KEY }}
          YIFFREST_API_KEY: ${{ secrets.YIFFREST_API_KEY }}
          GELBOORU_API_KEY: ${{ secrets.GELBOORU_API_KEY }}
          GELBOORU_USER_ID: ${{ secrets.GELBOORU_USER_ID }}

  publish-jsr:
    name: Publish to JSR
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - run: deno publish

  publish-npm:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
      - name: Build NPM package
        run: deno run -A scripts/build_npm.ts ${GITHUB_REF_NAME#v}
      - name: Publish
        run: npm publish ./npm_dist --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
